Improved some scritps and other things

diff --git a/daily-scripts/cscript b/daily-scripts/cscript
--- a/daily-scripts/cscript
+++ b/daily-scripts/cscript
@@ -6,6 +6,11 @@ else
   read -p 'Enter Script Name: ' script
 fi
 
+if [[ -f $script ]]; then
+  echo "ERROR: a file with this name already exists."
+  exit 1
+fi
+
 touch $script
 chmod +x $script
 
